name: spreadlee
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.17+164

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  permission_handler: ^11.2.0
  open_file: ^3.3.2
  url_launcher: ^6.2.4
  equatable: ^2.0.5
  webview_flutter: ^4.7.0
  stop_watch_timer: ^2.0.0
  syncfusion_flutter_pdfviewer:
  intl: ^0.20.2
#  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.4.0
  google_maps_flutter_ios: ^2.4.0
  google_maps_flutter_platform_interface: ^2.4.0
  google_maps_flutter_web: ^0.5.0
  geolocator: ^10.1.0
  geolocator_android: ^4.0.0
  geolocator_apple: ^2.0.0
  geolocator_platform_interface: ^4.0.0
  geolocator_web: ^2.2.1
  google_static_maps_controller: ^1.0.0
  web_socket_channel: ^2.4.0
  google_places_flutter: ^2.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^8.1.4
  easy_localization: ^3.0.7+1
  http: ^1.3.0
#  connectivity_plus: 6.1.5
  connectivity_plus: ^6.1.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.9.3
  flutter_phoenix: ^1.1.1
  fluttertoast: ^8.2.12
  jwt_decoder: ^2.0.1
#  pdfx: ^2.9.1
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  check_vpn_connection: ^0.0.2
  csc_picker_plus: ^0.0.3
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  file_picker: ^10.1.9
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  flutter_pdfview: ^1.3.2
  cross_file: ^0.3.3
  flutter_slidable: ^3.0.1
  phone_form_field: 
  multi_select_flutter: 
# hyperpay_plugin: ^3.1.4
  mime_type: 
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1
  easy_debounce: ^2.0.3
  record: ^6.0.0
  font_awesome_flutter: ^10.7.0
  socket_io_client: ^2.0.0
  app_settings: ^5.1.1
  flutter_localizations:
    sdk: flutter
#  flutter_local_notifications: ^16.3.2
  just_audio: ^0.9.36
  video_player: ^2.8.6
  chewie: ^1.8.1
  cached_video_player_plus: ^2.0.0
  video_thumbnail: ^0.5.3
  audio_waveforms: ^1.0.5
#  document_file_save_plus:
  share_plus: ^7.2.1
  image_gallery_saver_plus: ^4.0.1
#  image_gallery_saver_plus: ^4.0.1
  google_fonts: ^6.1.0
  bidi: ^2.0.0
  wechat_assets_picker: ^9.8.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'     

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
   
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/pdfs/
    - assets/jsons/
    - assets/icons/
    - assets/localization/ar-SA.json
    - assets/localization/en-US.json
  fonts:
        
    - family: 'Amiri'
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-BoldItalic.ttf
          weight: 700
          style: italic
    - family: 'Hacen Tunisia'
      fonts:
        - asset: assets/fonts/Hacen Tunisia.ttf
        - asset: assets/fonts/Hacen Tunisia Bold.ttf
          weight: 700
    - family: Icons1
      fonts:
        - asset: assets/fonts/icons1.ttf
    - family: Icons2
      fonts:
        - asset: assets/fonts/icons2.ttf
    - family: Icon3
      fonts:
        - asset: assets/fonts/icon3.ttf
    - family: Dot
      fonts:
        - asset: assets/fonts/dot.ttf
    - family: IconsChat
      fonts:
        - asset: assets/fonts/icons-chat.ttf
    - family: Paypass
      fonts:
        - asset: assets/fonts/paypass.ttf
    - family: CheckDouble
      fonts:
        - asset: assets/fonts/check-double.ttf
    - family: Send
      fonts:
        - asset: assets/fonts/send.ttf
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: Wait
      fonts:
        - asset: assets/fonts/wait.ttf
    - family: Pdf
      fonts:
        - asset: assets/fonts/pdf.ttf
    - family: Drawer
      fonts:
        - asset: assets/fonts/drawer.ttf
    - family: Trash
      fonts:
        - asset: assets/fonts/trash.ttf
    - family: Ics
      fonts:
        - asset: assets/fonts/ics.ttf
    - family: Profile
      fonts:
        - asset: assets/fonts/profile.ttf
    - family: OtherDrawer
      fonts:
        - asset: assets/fonts/other-drawer.ttf
    - family: TaxInvoice
      fonts:
        - asset: assets/fonts/tax-invoice.ttf
    - family: Search
      fonts:
        - asset: assets/fonts/search.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
